### ISSUE TITLE
Migrate to tox-dev and v4 support

### ISSUE THREAD

**Issue by gaborbernat** [apihackers/tox-asdf#8]
Hello, would you consider moving the project under the tox-dev umbrella? See documentation under https://tox.readthedocs.io/en/rewrite/plugins.html#adoption-of-a-plugin-under-tox-dev-github-organization 

Furthermore, tox v4 is getting ready and we'd like to make sure this plugin is supported from day 1, we're collecting feature gaps for this under https://github.com/tox-dev/tox/issues/1974. Would be great if you could join our development chat under https://discord.gg/tox so we can assist with this. If you do so please drop in a line in the `#plugin` chat with the name of the repository you maintain. Thanks!

**Comment by ssbarnea** [comment]
Yep, w/o tox v4 support this plugin is useless and v4 was released long time ago.

**Comment by hsheth2** [comment]
In case other folks come across this issue: tox 4 no longer requires a plugin to find python versions. Instead it uses virtualenv discovery (see details here https://tox.wiki/en/latest/plugins.html#tox-get-python-executable)

This is what ultimately worked for me:
```bash
pip install virtualenv-asdf
export VIRTUALENV_DISCOVERY=asdf
# tox commands work now!
```

**Comment by ssbarnea** [comment]
@hsheth2 Thanks for the hint. I made tox recognize asdf even without this but with a small trick, i had to activate asdf for bash too, not only for zsh (default shell on macos). Somehow, i have the impression that bash is used somewhere in detection process instead of the default shell and that prevents tox from finding asdf.

**Comment by hsheth2** [comment]
For what it's worth, I found that using multiple versions in `asdf local` worked, and didn't require `virtualenv-asdf`.

```sh
asdf local python 3.10.13 3.8.18
```

Via https://www.jroeder.net/2019/12/04/asdf-poetry-tox-and-travis-ci/
